import time
from enum import IntEnum
import threading

import numpy as np
from scipy.spatial.transform import Rotation as R

from spark_agent.real.unitree_g1.unitree_g1_idl_struct import DataBuffer, LowStateDataStruct
from spark_agent.real.unitree_g1.unitree_g1_real_sport_mode_agent import (
    UnitreeControlLevel,
    UnitreeG1RealSportModeAgent,
)
from spark_robot import RobotConfig, UnitreeG1WholeBodyDynamic1Config


Dex3_Num_Motors = 7
kTopicDex3LeftCommand = "rt/dex3/left/cmd"
kTopicDex3RightCommand = "rt/dex3/right/cmd"
kTopicDex3LeftState = "rt/dex3/left/state"
kTopicDex3RightState = "rt/dex3/right/state"


class Dex3_1_Left_JointIndex(IntEnum):
    kLeftHandThumb0 = 0
    kLeftHandThumb1 = 1
    kLeftHandThumb2 = 2
    kLeftHandMiddle0 = 3
    kLeftHandMiddle1 = 4
    kLeftHandIndex0 = 5
    kLeftHandIndex1 = 6


class Dex3_1_Right_JointIndex(IntEnum):
    kRightHandThumb0 = 0
    kRightHandThumb1 = 1
    kRightHandThumb2 = 2
    kRightHandIndex0 = 3
    kRightHandIndex1 = 4
    kRightHandMiddle0 = 5
    kRightHandMiddle1 = 6


class UnitreeG1RealWholeBodyAgent(UnitreeG1RealSportModeAgent):
    """Real Unitree G1 low-level whole-body agent.

    This agent consumes joint-position targets generated by a policy such as
    UnitreeG1WBTPolicy. It keeps the transport, hand, digital-twin, and motor
    command plumbing from the legacy real WBT agent, but it does not run the
    WBT loco/squat neural policies inside the agent.
    """

    def __init__(self, robot_cfg: RobotConfig, **kwargs):
        self.body_robot_cfg_for_targets = UnitreeG1WholeBodyDynamic1Config()
        self.unitree_network_interface = kwargs.get(
            "unitree_network_interface", kwargs.get("net", "")
        )
        self.with_hand = "WithHand" in robot_cfg.__class__.__name__
        self.enable_hand_control = bool(kwargs.get("enable_hand_control", self.with_hand))
        self.enable_hand_state_monitor = bool(
            kwargs.get("enable_hand_state_monitor", self.with_hand)
        )
        self.hand_state_debug_print = bool(kwargs.get("hand_state_debug_print", False))
        self.hand_state_zero_invalid = bool(kwargs.get("hand_state_zero_invalid", True))
        if self.with_hand:
            self._init_hand_control(**kwargs)
        self._hand_state_lock = threading.Lock()
        self.left_hand_q_sensor = np.full(Dex3_Num_Motors, np.nan, dtype=float)
        self.right_hand_q_sensor = np.full(Dex3_Num_Motors, np.nan, dtype=float)
        self.left_hand_state_timestamp = None
        self.right_hand_state_timestamp = None
        self._last_hand_state_debug_time = 0.0
        self._last_hand_state_warn_time = 0.0
        self._last_hand_command_debug_time = 0.0
        self.left_gripper_goal = False
        self.right_gripper_goal = False
        self.left_gripper_debug_state = False
        self.right_gripper_debug_state = False
        self._init_real_robot_location_state(**kwargs)
        super().__init__(robot_cfg, **kwargs)
        self.enable_digital_twin = bool(kwargs.get("enable_digital_twin", True))
        self.digital_twin_backend = str(kwargs.get("digital_twin_backend", "mujoco"))
        self.digital_twin = None
        if self.enable_digital_twin:
            self._init_digital_twin(robot_cfg, **kwargs)
        self.last_control_timestamp = time.time()

    def _init_sport_mode(self):
        self.body_robot_cfg_for_targets = UnitreeG1WholeBodyDynamic1Config()
        self.default_dof_pos = self._default_real_motor_pos()
        self.default_pos_lower_body = self.default_dof_pos[:12].copy()
        self.target_pos = self.default_dof_pos.copy()
        self.target_vel = np.zeros_like(self.target_pos)

    def _default_real_motor_pos(self):
        default_pos = []
        for motor in self.robot_cfg.RealMotors:
            if hasattr(self.robot_cfg.DoFs, motor.name):
                dof = getattr(self.robot_cfg.DoFs, motor.name)
                default_pos.append(self.robot_cfg.DefaultDoFVal[dof])
            else:
                default_pos.append(0.0)
        return np.asarray(default_pos, dtype=float)

    def _default_full_dof_pos(self):
        return np.asarray(
            [self.robot_cfg.DefaultDoFVal[dof] for dof in self.robot_cfg.DoFs],
            dtype=float,
        )

    def _body_default_qpos(self):
        return np.asarray(
            [
                self.body_robot_cfg_for_targets.DefaultDoFVal[dof]
                for dof in self.body_robot_cfg_for_targets.DoFs
            ],
            dtype=float,
        )

    def _move_to_default_pos(self):
        print("Moving to default pos.")
        total_time = 2.0
        num_step = max(1, int(total_time / self.dt))
        self.default_dof_pos = self._default_real_motor_pos()
        init_dof_pos = self.get_real_motor_q()

        for i in range(num_step):
            alpha = i / num_step
            target = init_dof_pos * (1.0 - alpha) + self.default_dof_pos * alpha
            self._set_motor_cmd(
                cmd_q=target,
                cmd_dq=np.zeros(self.num_real_motor),
                cmd_tau=np.zeros(self.num_real_motor),
                cmd_kp=self.kps,
                cmd_kd=self.kds,
                weight=0.0,
            )
            if self.send_cmd:
                self._send_cmd(self.cmd_msg)
            print("Moving to default pos: {:.2f}%".format(alpha * 100), end="\r")
            time.sleep(self.dt)

        print("Enter default pos state.")
        print("Waiting for the Right_Start_Long signal...")

    def _target_from_dof_pos(self, target_dof_pos):
        target = np.asarray(target_dof_pos, dtype=float).reshape(-1)

        if target.shape[0] == self.num_real_motor:
            return target.copy()

        values = []
        if target.shape[0] == len(self.robot_cfg.DoFs):
            for motor in self.robot_cfg.RealMotors:
                if not hasattr(self.robot_cfg.DoFs, motor.name):
                    raise KeyError(f"No robot DoF named {motor.name}")
                values.append(target[int(getattr(self.robot_cfg.DoFs, motor.name))])
            return np.asarray(values, dtype=float)

        if target.shape[0] == len(self.body_robot_cfg_for_targets.DoFs):
            for motor in self.robot_cfg.RealMotors:
                if not hasattr(self.body_robot_cfg_for_targets.DoFs, motor.name):
                    raise KeyError(f"No whole-body DoF named {motor.name}")
                values.append(
                    target[int(getattr(self.body_robot_cfg_for_targets.DoFs, motor.name))]
                )
            return np.asarray(values, dtype=float)

        raise ValueError(
            "target_dof_pos must be full robot DoF position, canonical whole-body qpos, "
            f"or real motor position; got shape {target.shape}"
        )

    def _coerce_real_motor_position_target(self, action_info):
        if "target_actuated_pos" in action_info:
            target = np.asarray(action_info["target_actuated_pos"], dtype=float).reshape(-1)
            if target.shape[0] != self.num_real_motor:
                raise ValueError(
                    f"target_actuated_pos must have {self.num_real_motor} entries, got {target.shape[0]}"
                )
            return target.copy()

        if "target_dof_pos" in action_info:
            return self._target_from_dof_pos(action_info["target_dof_pos"])

        raise KeyError(
            "UnitreeG1RealWholeBodyAgent expects action_info['target_actuated_pos'] "
            "or action_info['target_dof_pos'] from a whole-body policy."
        )

    def _coerce_real_motor_velocity_target(self, action_info):
        if "target_actuated_vel" in action_info:
            target = np.asarray(action_info["target_actuated_vel"], dtype=float).reshape(-1)
        elif "target_dof_vel" in action_info:
            target = np.asarray(action_info["target_dof_vel"], dtype=float).reshape(-1)
        else:
            return np.zeros(self.num_real_motor, dtype=float)

        if target.shape[0] == self.num_real_motor:
            return target.copy()

        if target.shape[0] == len(self.robot_cfg.DoFs):
            values = []
            for motor in self.robot_cfg.RealMotors:
                if not hasattr(self.robot_cfg.DoFs, motor.name):
                    raise KeyError(f"No robot DoF named {motor.name}")
                values.append(target[int(getattr(self.robot_cfg.DoFs, motor.name))])
            return np.asarray(values, dtype=float)

        return np.zeros(self.num_real_motor, dtype=float)

    def _gains_from_action_info(self, action_info):
        kps = np.asarray(
            action_info.get("target_actuated_kps", action_info.get("motor_kps", self.kps)),
            dtype=float,
        ).reshape(-1)
        kds = np.asarray(
            action_info.get("target_actuated_kds", action_info.get("motor_kds", self.kds)),
            dtype=float,
        ).reshape(-1)
        if kps.shape[0] != self.num_real_motor:
            kps = np.asarray(self.kps, dtype=float)
        if kds.shape[0] != self.num_real_motor:
            kds = np.asarray(self.kds, dtype=float)
        return kps, kds

    def _clip_real_motor_target(self, target_pos):
        target_pos = np.asarray(target_pos, dtype=float).reshape(-1).copy()
        for idx, motor in enumerate(self.robot_cfg.RealMotors):
            joint_pos_min, joint_pos_max = self.robot_cfg.RealMotorPosLimit.get(
                motor, (-np.inf, np.inf)
            )
            target_pos[idx] = np.clip(target_pos[idx], joint_pos_min, joint_pos_max)
        return target_pos

    def _full_dof_from_real_motor_target(self, target_pos):
        if self.dof_pos_cmd is not None and len(self.dof_pos_cmd) == len(self.robot_cfg.DoFs):
            dof_pos = np.asarray(self.dof_pos_cmd, dtype=float).copy()
        else:
            dof_pos = self._default_full_dof_pos()

        for idx, motor in enumerate(self.robot_cfg.RealMotors):
            if hasattr(self.robot_cfg.DoFs, motor.name):
                dof_pos[int(getattr(self.robot_cfg.DoFs, motor.name))] = target_pos[idx]
        return dof_pos

    def _full_dof_vel_from_real_motor_target(self, target_vel):
        dof_vel = np.zeros(len(self.robot_cfg.DoFs), dtype=float)
        for idx, motor in enumerate(self.robot_cfg.RealMotors):
            if hasattr(self.robot_cfg.DoFs, motor.name):
                dof_vel[int(getattr(self.robot_cfg.DoFs, motor.name))] = target_vel[idx]
        return dof_vel

    def _body_feedback_from_full_dof(self, full_dof_pos, full_dof_vel):
        full_dof_pos = np.asarray(full_dof_pos, dtype=float).reshape(-1)
        full_dof_vel = np.asarray(full_dof_vel, dtype=float).reshape(-1)
        body_qpos = self._body_default_qpos()
        body_qvel = np.zeros(len(self.body_robot_cfg_for_targets.DoFs) - 1, dtype=float)
        try:
            body_qvel[3:6] = np.asarray(self.get_imu_gyroscope(), dtype=float).reshape(3)
        except Exception:
            pass

        for name in (
            "LinearX",
            "LinearY",
            "LinearZ",
            "QuaternionW",
            "QuaternionX",
            "QuaternionY",
            "QuaternionZ",
        ):
            if hasattr(self.robot_cfg.DoFs, name):
                body_qpos[int(getattr(self.body_robot_cfg_for_targets.DoFs, name))] = full_dof_pos[
                    int(getattr(self.robot_cfg.DoFs, name))
                ]

        for motor in self.robot_cfg.RealMotors:
            if not hasattr(self.body_robot_cfg_for_targets.DoFs, motor.name):
                continue
            body_qpos_idx = int(getattr(self.body_robot_cfg_for_targets.DoFs, motor.name))
            body_qvel_idx = body_qpos_idx - 1
            if hasattr(self.robot_cfg.DoFs, motor.name):
                dof_idx = int(getattr(self.robot_cfg.DoFs, motor.name))
                body_qpos[body_qpos_idx] = full_dof_pos[dof_idx]
                if 0 <= body_qvel_idx < body_qvel.shape[0] and dof_idx < full_dof_vel.shape[0]:
                    body_qvel[body_qvel_idx] = full_dof_vel[dof_idx]

        return body_qpos, body_qvel

    def _init_real_robot_location_state(self, **kwargs):
        self.real_robot_location_topic = kwargs.get(
            "real_robot_location_topic", "/real_robot_location"
        )
        self.real_robot_location_enabled = bool(kwargs.get("real_robot_location_enabled", False))
        self.real_robot_location_timeout = float(kwargs.get("real_robot_location_timeout", 0.5))
        self.real_robot_location_orientation_source = str(
            kwargs.get("real_robot_location_orientation_source", "topic")
        ).lower()
        self.real_robot_location_align_imu_to_pose = bool(
            kwargs.get("real_robot_location_align_imu_to_pose", False)
        )
        self.real_robot_location_filter_alpha = float(
            kwargs.get("real_robot_location_filter_alpha", 1.0)
        )
        self.default_robot_base_height = 0.793
        self._real_robot_location_lock = threading.Lock()
        self._real_robot_location_T = None
        self._real_robot_location_timestamp = None
        self._imu_world_rotation_correction = None
        self._real_robot_location_sub = None
        self._last_real_robot_location_warn_time = 0.0
        self._last_robot_base_frame = np.eye(4, dtype=np.float64)
        self._last_robot_base_frame[2, 3] = self.default_robot_base_height

    def attach_ros1_real_robot_location(self, rospy_module, msg_type):
        if not self.real_robot_location_enabled or not self.real_robot_location_topic:
            return False
        if self._real_robot_location_sub is not None:
            return True
        self._real_robot_location_sub = rospy_module.Subscriber(
            self.real_robot_location_topic,
            msg_type,
            self._real_robot_location_callback,
        )
        print(f"Subscribing to real robot location topic: {self.real_robot_location_topic}")
        return True

    def attach_ros2_real_robot_location(self, node, msg_type, qos):
        if not self.real_robot_location_enabled or not self.real_robot_location_topic:
            return False
        if self._real_robot_location_sub is not None:
            return True
        self._real_robot_location_sub = node.create_subscription(
            msg_type,
            self.real_robot_location_topic,
            self._real_robot_location_callback,
            qos,
        )
        print(f"Subscribing to real robot location topic: {self.real_robot_location_topic}")
        return True

    def _warn_real_robot_location_throttle(self, message):
        now = time.time()
        if now - self._last_real_robot_location_warn_time > 1.0:
            print(message)
            self._last_real_robot_location_warn_time = now

    def _real_robot_location_callback(self, msg):
        values = np.asarray(msg.data, dtype=np.float64).reshape(-1)
        if values.size < 16:
            self._warn_real_robot_location_throttle(
                f"{self.real_robot_location_topic} expects at least 16 values, got {values.size}"
            )
            return

        robot_location = values[:16].reshape(4, 4)
        if not np.all(np.isfinite(robot_location)):
            self._warn_real_robot_location_throttle(
                f"{self.real_robot_location_topic} contains non-finite values"
            )
            return

        robot_location = robot_location.copy()
        robot_location[3, :] = np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float64)
        alpha = np.clip(self.real_robot_location_filter_alpha, 0.0, 1.0)
        with self._real_robot_location_lock:
            if self._real_robot_location_T is not None and alpha < 1.0:
                robot_location[:3, 3] = (
                    alpha * robot_location[:3, 3]
                    + (1.0 - alpha) * self._real_robot_location_T[:3, 3]
                )
            self._real_robot_location_T = robot_location
            self._real_robot_location_timestamp = time.time()
            if (
                self.real_robot_location_align_imu_to_pose
                and self._imu_world_rotation_correction is None
            ):
                imu_rotation = self._imu_rotation_matrix()
                self._imu_world_rotation_correction = robot_location[:3, :3] @ imu_rotation.T

    def _latest_real_robot_location(self):
        with self._real_robot_location_lock:
            if self._real_robot_location_T is None or self._real_robot_location_timestamp is None:
                return None, None
            return (
                self._real_robot_location_T.copy(),
                time.time() - self._real_robot_location_timestamp,
            )

    def _normalized_imu_quaternion(self):
        try:
            imu_q = np.asarray(self.get_imu_quaternion(), dtype=np.float64).reshape(4)
        except Exception:
            return np.array([1.0, 0.0, 0.0, 0.0], dtype=np.float64)
        norm = float(np.linalg.norm(imu_q))
        if norm > 1e-12:
            return imu_q / norm
        return np.array([1.0, 0.0, 0.0, 0.0], dtype=np.float64)

    def _imu_rotation_matrix(self):
        imu_q = self._normalized_imu_quaternion()
        return R.from_quat([imu_q[1], imu_q[2], imu_q[3], imu_q[0]]).as_matrix()

    def _world_aligned_imu_rotation_matrix(self):
        imu_rotation = self._imu_rotation_matrix()
        with self._real_robot_location_lock:
            correction = None
            if self._imu_world_rotation_correction is not None:
                correction = self._imu_world_rotation_correction.copy()
        if correction is None:
            return imu_rotation
        return correction @ imu_rotation

    def _fallback_robot_base_frame(self):
        robot_base_frame = np.eye(4, dtype=np.float64)
        robot_base_frame[2, 3] = self.default_robot_base_height
        robot_base_frame[:3, :3] = self._world_aligned_imu_rotation_matrix()
        return robot_base_frame

    def _robot_base_frame_from_location_sources(self):
        robot_base_frame = None
        if self.real_robot_location_enabled:
            real_robot_location, location_age = self._latest_real_robot_location()
            if real_robot_location is None:
                self._warn_real_robot_location_throttle(
                    f"Waiting for real robot location on {self.real_robot_location_topic}"
                )
            elif location_age is not None and location_age > self.real_robot_location_timeout:
                self._warn_real_robot_location_throttle(
                    f"Real robot location is stale ({location_age:.3f}s); holding previous base frame"
                )
                robot_base_frame = self._last_robot_base_frame.copy()
            else:
                robot_base_frame = real_robot_location

        if robot_base_frame is None:
            robot_base_frame = self._fallback_robot_base_frame()
        if self.real_robot_location_orientation_source in ("imu", "robot_imu"):
            robot_base_frame[:3, :3] = self._world_aligned_imu_rotation_matrix()
        robot_base_frame[3, :] = np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float64)
        self._last_robot_base_frame = robot_base_frame.copy()
        return robot_base_frame

    def _base_frame_to_mujoco_quaternion(self, robot_base_frame):
        quat_xyzw = R.from_matrix(robot_base_frame[:3, :3]).as_quat()
        return np.array([quat_xyzw[3], quat_xyzw[0], quat_xyzw[1], quat_xyzw[2]], dtype=np.float64)

    def _base_virtual_dof_values(self, robot_base_frame):
        quat_wxyz = self._base_frame_to_mujoco_quaternion(robot_base_frame)
        euler_xyz = R.from_matrix(robot_base_frame[:3, :3]).as_euler("xyz", degrees=False)
        return {
            "LinearX": float(robot_base_frame[0, 3]),
            "LinearY": float(robot_base_frame[1, 3]),
            "LinearZ": float(robot_base_frame[2, 3]),
            "QuaternionW": float(quat_wxyz[0]),
            "QuaternionX": float(quat_wxyz[1]),
            "QuaternionY": float(quat_wxyz[2]),
            "QuaternionZ": float(quat_wxyz[3]),
            "RotPitch": float(euler_xyz[1]),
            "RotYaw": float(euler_xyz[2]),
        }

    def _overwrite_base_virtual_dof_feedback(self, dof_pos, robot_base_frame):
        base_values = self._base_virtual_dof_values(robot_base_frame)
        for dof in self.robot_cfg.DoFs:
            if dof.name in base_values:
                dof_pos[int(dof)] = base_values[dof.name]
        return dof_pos

    def _real_dof_for_robot_dof(self, dof):
        if dof in self.robot_cfg.DoF_to_RealDoF:
            return self.robot_cfg.DoF_to_RealDoF[dof]
        if hasattr(self.robot_cfg, "RealDoFs") and hasattr(self.robot_cfg.RealDoFs, dof.name):
            return getattr(self.robot_cfg.RealDoFs, dof.name)
        return None

    def _init_digital_twin(self, robot_cfg: RobotConfig, **kwargs):
        if self.digital_twin_backend != "mujoco":
            raise ValueError("The Unitree real-agent digital twin currently supports MuJoCo only")
        import mujoco

        from spark_agent.simulation.mujoco.unitree_g1.unitree_g1_whole_body_mujoco_agent import (
            UnitreeG1WholeBodyMujocoAgent,
        )

        kwargs["enable_viewer"] = True
        self.digital_twin = UnitreeG1WholeBodyMujocoAgent(robot_cfg, **kwargs)
        bit = int(mujoco.mjtDisableBit.mjDSBL_CONTACT)
        self.digital_twin.model.opt.disableflags |= bit
        mujoco.mj_forward(self.digital_twin.model, self.digital_twin.data)
        self._digital_twin_sync_enabled = True
        threading.Thread(
            target=self._digital_twin_sync_thread,
            kwargs={"sync_hz": kwargs.get("digital_twin_sync_hz", 500.0)},
            daemon=True,
        ).start()

    def _latest_monitored_hand_q(self, side: str):
        with self._hand_state_lock:
            if side == "left":
                if self.left_hand_state_timestamp is None:
                    return None
                return self.left_hand_q_sensor.copy()
            if self.right_hand_state_timestamp is None:
                return None
            return self.right_hand_q_sensor.copy()

    def _warn_hand_state_throttle(self, message):
        now = time.time()
        if now - self._last_hand_state_warn_time > 1.0:
            print(message)
            self._last_hand_state_warn_time = now

    def _set_monitored_hand_q(self, side: str, values: np.ndarray):
        values = np.asarray(values, dtype=float).reshape(Dex3_Num_Motors)
        if self.hand_state_zero_invalid and np.allclose(values, 0.0, atol=1.0e-8):
            self._warn_hand_state_throttle(
                f"Ignoring all-zero Dex3 {side} hand state; waiting for valid rt/dex3/{side}/state data"
            )
            return
        with self._hand_state_lock:
            if side == "left":
                self.left_hand_q_sensor = values.copy()
                self.left_hand_state_timestamp = time.time()
            else:
                self.right_hand_q_sensor = values.copy()
                self.right_hand_state_timestamp = time.time()

    def _model_order_hand_feedback(self) -> tuple[np.ndarray, np.ndarray]:
        left_target = self._latest_monitored_hand_q("left")
        right_target = self._latest_monitored_hand_q("right")
        if left_target is None:
            left_target = getattr(self, "left_hand_q_target", np.zeros(Dex3_Num_Motors))
        if right_target is None:
            right_target = getattr(self, "right_hand_q_target", np.zeros(Dex3_Num_Motors))
        return (
            np.asarray(left_target, dtype=float).reshape(Dex3_Num_Motors),
            np.asarray(right_target, dtype=float).reshape(Dex3_Num_Motors),
        )

    def _maybe_print_hand_state_debug(self):
        if not self.hand_state_debug_print:
            return
        now = time.time()
        if now - self._last_hand_state_debug_time < 1.0:
            return
        self._last_hand_state_debug_time = now
        with self._hand_state_lock:
            left_raw = (
                None if self.left_hand_state_timestamp is None else self.left_hand_q_sensor.copy()
            )
            right_raw = (
                None if self.right_hand_state_timestamp is None else self.right_hand_q_sensor.copy()
            )
            left_age = (
                None
                if self.left_hand_state_timestamp is None
                else now - self.left_hand_state_timestamp
            )
            right_age = (
                None
                if self.right_hand_state_timestamp is None
                else now - self.right_hand_state_timestamp
            )
        left_model, right_model = self._model_order_hand_feedback()
        left_source = "sensor" if left_raw is not None else "fallback"
        right_source = "sensor" if right_raw is not None else "fallback"

        def fmt(values):
            if values is None:
                return "None"
            return np.array2string(np.asarray(values), precision=3, suppress_small=True)

        def fmt_age(age):
            return "None" if age is None else f"{age:.3f}s"

        print(
            "[Dex3 hand monitor] "
            f"left={left_source} age={fmt_age(left_age)} raw={fmt(left_raw)} model={fmt(left_model)} | "
            f"right={right_source} age={fmt_age(right_age)} raw={fmt(right_raw)} model={fmt(right_model)}"
        )

    def _overwrite_model_order_hand_feedback(self, dof_pos: np.ndarray) -> np.ndarray:
        dof_pos = np.asarray(dof_pos, dtype=float).copy()
        if not (self.with_hand and dof_pos.shape[0] >= 50):
            return dof_pos
        left_hand, right_hand = self._model_order_hand_feedback()
        dof_pos[29:36] = left_hand
        dof_pos[43:50] = right_hand
        return dof_pos

    def _try_sync_digital_twin_once(self) -> bool:
        if getattr(self, "digital_twin", None) is None:
            return False
        if getattr(self, "_low_state_buffer", None) is None:
            return False
        if self._low_state_buffer.GetData() is None:
            return False

        qpos = self.digital_twin.data.qpos.copy()
        base_T = self._robot_base_frame_from_location_sources()
        qpos[0:3] = base_T[:3, 3]
        qpos[3:7] = self._base_frame_to_mujoco_quaternion(base_T)

        real_q_all = self.get_all_motor_q()
        qpos[7:22] = real_q_all[:15]
        qpos[22:29] = real_q_all[15:22]
        qpos[36:43] = real_q_all[22:29]
        if self.with_hand and qpos.shape[0] >= 50:
            left_hand, right_hand = self._model_order_hand_feedback()
            qpos[29:36] = left_hand
            qpos[43:50] = right_hand

        self.robot_base_goal = base_T @ self.digital_twin.base_goal_debug_frame
        self.digital_twin._set_dof_pos(qpos)
        self.digital_twin._post_control_processing()
        self.digital_twin.render_sphere(
            self.robot_base_goal[:3, 3],
            np.eye(3),
            0.1 * np.ones(3),
            [48 / 255, 245 / 255, 93 / 255, 0.3],
        )
        self.digital_twin.render_coordinate_frame(self.robot_base_goal, 0.2)
        self.digital_twin.viewer.sync()
        self.digital_twin.renderer.update_scene(self.digital_twin.data)
        return True

    def _digital_twin_sync_thread(self, sync_hz: float = 200.0) -> None:
        period = 1.0 / float(sync_hz)
        while True:
            if getattr(self, "_digital_twin_sync_enabled", True):
                try:
                    self._try_sync_digital_twin_once()
                except Exception:
                    pass
            time.sleep(period)

    def _setup_robot(self):
        from unitree_sdk2py.core.channel import ChannelFactoryInitialize

        if self.unitree_network_interface:
            print(
                f"Initializing Unitree DDS channel on network interface: {self.unitree_network_interface}"
            )
            ChannelFactoryInitialize(0, self.unitree_network_interface)
        else:
            ChannelFactoryInitialize()
        self._init_sport_mode()

    def _setup_subscribers(self):
        from unitree_sdk2py.core.channel import ChannelSubscriber
        from unitree_sdk2py.idl.unitree_hg.msg.dds_ import HandState_, LowCmd_, LowState_
        from unitree_sdk2py.idl.unitree_go.msg.dds_._SportModeState_ import SportModeState_

        self._low_state_suber = ChannelSubscriber("rt/lowstate", LowState_)
        self._low_state_suber.Init()
        self._low_state_buffer = DataBuffer()
        if self.control_level == UnitreeControlLevel.HIGH:
            self._high_state_suber = ChannelSubscriber("rt/odommodestate", SportModeState_)
            self._high_state_suber.Init()
            self._high_state_buffer = DataBuffer()

        self._cmd_suber = ChannelSubscriber(
            "rt/arm_sdk" if self.control_level == UnitreeControlLevel.HIGH else "rt/lowcmd",
            LowCmd_,
        )
        self._cmd_suber.Init()
        self._cmd_buffer = DataBuffer()

        if self.with_hand and self.enable_hand_state_monitor:
            self._left_hand_state_suber = ChannelSubscriber(kTopicDex3LeftState, HandState_)
            self._left_hand_state_suber.Init()
            self._right_hand_state_suber = ChannelSubscriber(kTopicDex3RightState, HandState_)
            self._right_hand_state_suber.Init()

    def _state_sub_thread(self):
        while True:
            msg = self._low_state_suber.Read()
            if msg is not None:
                low_state = LowStateDataStruct()
                low_state.imu_rpy = msg.imu_state.rpy
                low_state.imu_quaternion = msg.imu_state.quaternion
                low_state.imu_gyroscope = msg.imu_state.gyroscope
                low_state.imu_accelerometer = msg.imu_state.accelerometer
                for idx, motor in enumerate(msg.motor_state):
                    low_state.motor_state[idx].q = motor.q
                    low_state.motor_state[idx].dq = motor.dq
                    low_state.motor_state[idx].ddq = motor.ddq
                    low_state.motor_state[idx].tau_est = motor.tau_est
                self._low_state_buffer.SetData(low_state)
                if not self.update_mode_machine_:
                    self.mode_machine_ = msg.mode_machine
                    self.update_mode_machine_ = True

    @staticmethod
    def _hand_q_from_state_msg(msg, joint_indices) -> np.ndarray:
        return np.array([msg.motor_state[joint_id].q for joint_id in joint_indices], dtype=float)

    def _hand_state_sub_thread(self):
        while True:
            left_msg = self._left_hand_state_suber.Read()
            if left_msg is not None:
                self._set_monitored_hand_q(
                    "left",
                    self._hand_q_from_state_msg(left_msg, Dex3_1_Left_JointIndex),
                )
            right_msg = self._right_hand_state_suber.Read()
            if right_msg is not None:
                self._set_monitored_hand_q(
                    "right",
                    self._hand_q_from_state_msg(right_msg, Dex3_1_Right_JointIndex),
                )
            time.sleep(0.002)

    def _start_sub_threads(self):
        threading.Thread(target=self._state_sub_thread, daemon=True).start()
        if self.with_hand and self.enable_hand_state_monitor:
            threading.Thread(target=self._hand_state_sub_thread, daemon=True).start()

        cnt = 0
        while not self._low_state_buffer.GetData():
            time.sleep(0.1)
            cnt += 1
            if cnt % 10 == 0:
                print("Waiting to receive Unitree state data...")
            if cnt > 100:
                raise TimeoutError("Failed to receive Unitree state data.")

    def _setup_publishers(self):
        from unitree_sdk2py.core.channel import ChannelPublisher
        from unitree_sdk2py.idl.unitree_hg.msg.dds_ import HandCmd_, LowCmd_

        self._cmd_pub = ChannelPublisher(
            "rt/arm_sdk" if self.control_level == UnitreeControlLevel.HIGH else "rt/lowcmd",
            LowCmd_,
        )
        self._cmd_pub.Init()
        if self.enable_hand_control:
            self._left_hand_cmd_pub = ChannelPublisher(kTopicDex3LeftCommand, HandCmd_)
            self._left_hand_cmd_pub.Init()
            self._right_hand_cmd_pub = ChannelPublisher(kTopicDex3RightCommand, HandCmd_)
            self._right_hand_cmd_pub.Init()

    def _initialize_motor_cmd(self):
        super()._initialize_motor_cmd()
        if self.enable_hand_control:
            self._initialize_hand_cmd()

    class _RIS_Mode:
        def __init__(self, id=0, status=0x01, timeout=0):
            self.motor_mode = 0
            self.id = id & 0x0F
            self.status = status & 0x07
            self.timeout = timeout & 0x01

        def _mode_to_uint8(self):
            self.motor_mode |= self.id & 0x0F
            self.motor_mode |= (self.status & 0x07) << 4
            self.motor_mode |= (self.timeout & 0x01) << 7
            return self.motor_mode

    def _initialize_hand_cmd(self):
        from unitree_sdk2py.idl.default import unitree_hg_msg_dds__HandCmd_

        self.left_hand_cmd_msg = unitree_hg_msg_dds__HandCmd_()
        for joint_id in Dex3_1_Left_JointIndex:
            ris_mode = self._RIS_Mode(id=joint_id, status=0x01)
            self.left_hand_cmd_msg.motor_cmd[joint_id].mode = ris_mode._mode_to_uint8()
            self.left_hand_cmd_msg.motor_cmd[joint_id].q = 0.0
            self.left_hand_cmd_msg.motor_cmd[joint_id].dq = 0.0
            self.left_hand_cmd_msg.motor_cmd[joint_id].tau = 0.0
            self.left_hand_cmd_msg.motor_cmd[joint_id].kp = self.hand_kp
            self.left_hand_cmd_msg.motor_cmd[joint_id].kd = self.hand_kd

        self.right_hand_cmd_msg = unitree_hg_msg_dds__HandCmd_()
        for joint_id in Dex3_1_Right_JointIndex:
            ris_mode = self._RIS_Mode(id=joint_id, status=0x01)
            self.right_hand_cmd_msg.motor_cmd[joint_id].mode = ris_mode._mode_to_uint8()
            self.right_hand_cmd_msg.motor_cmd[joint_id].q = 0.0
            self.right_hand_cmd_msg.motor_cmd[joint_id].dq = 0.0
            self.right_hand_cmd_msg.motor_cmd[joint_id].tau = 0.0
            self.right_hand_cmd_msg.motor_cmd[joint_id].kp = self.hand_kp
            self.right_hand_cmd_msg.motor_cmd[joint_id].kd = self.hand_kd

    def _initialize_robot_motor_parameters(self):
        self.kps = np.array(
            [
                100,
                100,
                100,
                150,
                40,
                40,
                100,
                100,
                100,
                150,
                40,
                40,
                300,
                300,
                300,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
                40,
            ],
            dtype=float,
        )
        self.kds = np.array(
            [
                2,
                2,
                2,
                4,
                2,
                2,
                2,
                2,
                2,
                4,
                2,
                2,
                3,
                3,
                3,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
            ],
            dtype=float,
        )
        self.tau_record = np.zeros(self.num_real_motor, dtype=np.float32)

    def reset_upper_body(self):
        self.reset({})

    def reset(self, agent_reset_info):
        self._move_to_default_pos()
        if self.enable_hand_control:
            self.left_gripper_goal = False
            self.right_gripper_goal = False
            self._send_control_hand({})

    def _create_damping_cmd(self, cmd):
        for motor_cmd in cmd.motor_cmd:
            motor_cmd.q = 0
            motor_cmd.dq = 0
            motor_cmd.kp = 0
            motor_cmd.kd = 8
            motor_cmd.tau = 0

    def _send_cmd(self, cmd):
        if abs(self.tau_record).max() > 100:
            print("large tau: ", np.arange(self.num_real_motor)[abs(self.tau_record) > 100])
            self._create_damping_cmd(self.cmd_msg)
            cmd = self.cmd_msg
        cmd.crc = self.crc.Crc(cmd)
        self._cmd_pub.Write(cmd)

    def _set_motor_cmd(self, cmd_q, cmd_dq, cmd_tau, cmd_kp, cmd_kd, weight=None):
        if weight is not None:
            self.weight_notUsedJoint = max(min(weight, 1.0), 0.0)
        self.cmd_msg.motor_cmd[self.kNotUsedJoint].q = self.weight_notUsedJoint**2
        current_q = self.get_real_motor_q()
        current_dq = self.get_real_motor_dq()
        for idx, joint in enumerate(self.robot_cfg.RealMotors):
            joint_pos_min, joint_pos_max = self.robot_cfg.RealMotorPosLimit.get(
                joint, (-np.inf, np.inf)
            )
            joint_q = (1 - self.cmd_q_lambda) * self.cmd_msg.motor_cmd[
                joint
            ].q + self.cmd_q_lambda * cmd_q[idx]
            joint_q = np.clip(joint_q, joint_pos_min, joint_pos_max)

            self.cmd_msg.motor_cmd[joint].mode = 1
            self.cmd_msg.mode_machine = self.mode_machine_
            self.cmd_msg.motor_cmd[joint].q = joint_q
            self.cmd_msg.motor_cmd[joint].dq = cmd_dq[idx]
            self.cmd_msg.motor_cmd[joint].tau = cmd_tau[idx]
            self.cmd_msg.motor_cmd[joint].kp = cmd_kp[idx]
            self.cmd_msg.motor_cmd[joint].kd = cmd_kd[idx]
            self.tau_record[joint] = (joint_q - current_q[joint]) * self.kps[joint] - current_dq[
                joint
            ] * self.kds[joint]

    def _init_hand_control(self, **kwargs):
        self.hand_kp = float(kwargs.get("hand_kp", 2.5))
        self.hand_kd = float(kwargs.get("hand_kd", 0.2))
        self.left_hand_close_pos = np.array([-0.4, 0.2, 0.9, -1.4, -0.9, -1.4, -0.9], dtype=float)
        self.left_hand_open_pos = np.array([-0.8, 0.2, 0.0, -1.0, -0.0, -1.0, -0.0], dtype=float)
        self.right_hand_close_pos = np.array([-0.4, -0.2, -0.9, 0.8, 0.9, 0.8, 0.9], dtype=float)
        self.right_hand_open_pos = np.array([-0.4, -0.2, -0.6, 0.8, 0.6, 0.8, 0.6], dtype=float)
        self.left_hand_upper_joint_limit = np.array(
            [1.05, 1.05, 1.75, 0.00, 0.00, 0.00, 0.00], dtype=float
        )
        self.left_hand_lower_joint_limit = np.array(
            [-1.05, -0.724, 0.0, -1.57, -1.75, -1.57, -1.75], dtype=float
        )
        self.right_hand_upper_joint_limit = np.array(
            [1.05, 0.742, 0.0, 1.57, 1.75, 1.57, 1.75], dtype=float
        )
        self.right_hand_lower_joint_limit = np.array(
            [-1.05, -1.05, -1.75, 0.0, 0.0, 0.0, 0.0], dtype=float
        )
        self.left_hand_q_target = self.left_hand_open_pos.copy()
        self.right_hand_q_target = self.right_hand_open_pos.copy()

    def _coerce_gripper_goal(self, goal_value, current_value: bool) -> bool:
        if goal_value is None:
            return bool(current_value)
        return bool(goal_value)

    def _resolve_hand_target(self, side: str, action_info: dict) -> np.ndarray:
        control_key = f"{side}_gripper_control"
        if control_key in action_info:
            target = np.asarray(action_info[control_key], dtype=float).reshape(-1)
            if target.size != Dex3_Num_Motors:
                raise ValueError(f"{control_key} must have {Dex3_Num_Motors} entries.")
            if side == "left":
                self.left_gripper_goal = bool(np.any(target > 1e-6))
                return np.clip(
                    target, self.left_hand_lower_joint_limit, self.left_hand_upper_joint_limit
                )
            self.right_gripper_goal = bool(np.any(target > 1e-6))
            return np.clip(
                target, self.right_hand_lower_joint_limit, self.right_hand_upper_joint_limit
            )

        goal_key = f"{side}_gripper_goal"
        if side == "left":
            self.left_gripper_goal = self._coerce_gripper_goal(
                action_info.get(goal_key, None), self.left_gripper_goal
            )
            target = self.left_hand_close_pos if self.left_gripper_goal else self.left_hand_open_pos
            return np.clip(
                target, self.left_hand_lower_joint_limit, self.left_hand_upper_joint_limit
            )

        self.right_gripper_goal = self._coerce_gripper_goal(
            action_info.get(goal_key, action_info.get("gripper_goal", None)),
            self.right_gripper_goal,
        )
        target = self.right_hand_close_pos if self.right_gripper_goal else self.right_hand_open_pos
        return np.clip(target, self.right_hand_lower_joint_limit, self.right_hand_upper_joint_limit)

    def _ctrl_dual_hand(self, left_q_target: np.ndarray, right_q_target: np.ndarray):
        for idx, joint_id in enumerate(Dex3_1_Left_JointIndex):
            self.left_hand_cmd_msg.motor_cmd[joint_id].q = float(left_q_target[idx])
        for idx, joint_id in enumerate(Dex3_1_Right_JointIndex):
            self.right_hand_cmd_msg.motor_cmd[joint_id].q = float(right_q_target[idx])
        if self.send_cmd:
            self._left_hand_cmd_pub.Write(self.left_hand_cmd_msg)
            self._right_hand_cmd_pub.Write(self.right_hand_cmd_msg)
        self._maybe_print_hand_command_debug(left_q_target, right_q_target)

    def _maybe_print_hand_command_debug(
        self, left_q_target: np.ndarray, right_q_target: np.ndarray
    ):
        if not self.hand_state_debug_print:
            return
        now = time.time()
        if now - self._last_hand_command_debug_time < 0.5:
            return
        self._last_hand_command_debug_time = now
        print(
            "[Dex3 hand command] "
            f"enabled={self.enable_hand_control} send_cmd={self.send_cmd} "
            f"left_goal={self.left_gripper_goal} right_goal={self.right_gripper_goal} "
            f"left_q={np.array2string(np.asarray(left_q_target), precision=3, suppress_small=True)} "
            f"right_q={np.array2string(np.asarray(right_q_target), precision=3, suppress_small=True)}"
        )

    def _send_control_hand(self, action_info: dict):
        if not self.enable_hand_control:
            return
        self.left_hand_q_target = self._resolve_hand_target("left", action_info)
        self.right_hand_q_target = self._resolve_hand_target("right", action_info)
        self._ctrl_dual_hand(self.left_hand_q_target, self.right_hand_q_target)

    def send_control(self, command: np.ndarray, **kwargs):
        action_info = kwargs.get("action_info", {})
        target_pos = self._clip_real_motor_target(
            self._coerce_real_motor_position_target(action_info)
        )
        target_vel = self._coerce_real_motor_velocity_target(action_info)
        kps, kds = self._gains_from_action_info(action_info)

        self.target_pos = target_pos.copy()
        self.target_vel = target_vel.copy()
        self.dof_pos_cmd = self._full_dof_from_real_motor_target(target_pos)
        self.dof_vel_cmd = self._full_dof_vel_from_real_motor_target(target_vel)
        self.dof_acc_cmd = np.zeros_like(self.dof_vel_cmd)

        self._send_control_hand(action_info)

        if self.send_cmd:
            self._set_motor_cmd(
                cmd_q=target_pos,
                cmd_dq=target_vel,
                cmd_tau=np.zeros(self.num_real_motor),
                cmd_kp=kps,
                cmd_kd=kds,
            )
            self._send_cmd(self.cmd_msg)

            control_period = self.dt * self.control_decimation
            current_control_timestamp = time.time()
            time_until_next_step = control_period - (
                current_control_timestamp - self.last_control_timestamp
            )
            if time_until_next_step > 0:
                time.sleep(time_until_next_step)
            self.last_control_timestamp = time.time()

    def get_feedback(self):
        ret = {}
        robot_base_frame = self._robot_base_frame_from_location_sources()
        ret["robot_base_frame"] = robot_base_frame

        real_robot_qpos = self.get_all_motor_q()
        real_robot_qvel = self.get_all_motor_dq()
        dof_pos_sensor_fbk = np.zeros(self.num_dof)
        dof_vel_sensor_fbk = np.zeros(self.num_dof)
        base_virtual_dof_values = self._base_virtual_dof_values(robot_base_frame)

        for dof in self.robot_cfg.DoFs:
            dof_idx = int(dof)
            if dof.name in base_virtual_dof_values:
                dof_pos_sensor_fbk[dof_idx] = base_virtual_dof_values[dof.name]
                if self.dof_vel_cmd is not None:
                    dof_vel_sensor_fbk[dof_idx] = self.dof_vel_cmd[dof_idx]
                continue

            real_dof = self._real_dof_for_robot_dof(dof)
            if real_dof is None:
                dof_pos_sensor_fbk[dof_idx] = self.robot_cfg.DefaultDoFVal[dof]
                continue

            dof_pos_sensor_fbk[dof_idx] = real_robot_qpos[real_dof]
            dof_vel_sensor_fbk[dof_idx] = real_robot_qvel[real_dof]

        dof_pos_sensor_fbk = self._overwrite_model_order_hand_feedback(dof_pos_sensor_fbk)
        self._maybe_print_hand_state_debug()

        ret["dof_pos_sensor_fbk"] = dof_pos_sensor_fbk.copy()
        ret["dof_vel_sensor_fbk"] = dof_vel_sensor_fbk.copy()

        if self.dof_pos_cmd is None:
            self.dof_pos_cmd = dof_pos_sensor_fbk.copy()
        if self.dof_vel_cmd is None:
            self.dof_vel_cmd = np.zeros(self.num_dof)
        if self.dof_acc_cmd is None:
            self.dof_acc_cmd = np.zeros(self.num_dof)

        ret["dof_pos_cmd"] = self.dof_pos_cmd
        ret["dof_vel_cmd"] = self.dof_vel_cmd
        ret["dof_acc_cmd"] = self.dof_acc_cmd

        dof_pos_fbk = self.dof_pos_cmd.copy()
        dof_pos_fbk = self._overwrite_base_virtual_dof_feedback(dof_pos_fbk, robot_base_frame)
        dof_pos_fbk = self._overwrite_model_order_hand_feedback(dof_pos_fbk)
        dof_vel_fbk = self.dof_vel_cmd.copy()

        ret["dof_pos_fbk"] = dof_pos_fbk
        ret["dof_vel_fbk"] = dof_vel_fbk
        ret["state"] = self._compose_cmd_state()

        twin = self.digital_twin
        if twin is None:
            ret["robot_goal_left_offset"] = self.left_goal_debug_frame.copy()
            ret["robot_goal_right_offset"] = self.right_goal_debug_frame.copy()
            ret["robot_goal_base_offset"] = self.base_goal_debug_frame.copy()
        else:
            ret["robot_goal_left_offset"] = twin.left_goal_debug_frame
            ret["robot_goal_right_offset"] = twin.right_goal_debug_frame
            ret["robot_goal_base_offset"] = twin.base_goal_debug_frame
            self.left_gripper_debug_state = bool(getattr(twin, "left_gripper_debug_state", False))
            self.right_gripper_debug_state = bool(getattr(twin, "right_gripper_debug_state", False))
        ret["left_gripper_debug_state"] = self.left_gripper_debug_state
        ret["right_gripper_debug_state"] = self.right_gripper_debug_state
        ret["left_gripper_goal"] = bool(self.left_gripper_goal)
        ret["right_gripper_goal"] = bool(self.right_gripper_goal)

        ret["qpos_fbk"] = dof_pos_sensor_fbk.copy()
        ret["qvel_fbk"] = dof_vel_sensor_fbk.copy()
        body_qpos, body_qvel = self._body_feedback_from_full_dof(ret["qpos_fbk"], ret["qvel_fbk"])
        ret["body_qpos_fbk"] = body_qpos
        ret["body_qvel_fbk"] = body_qvel
        ret["mujoco_qpos_fbk"] = ret["qpos_fbk"]
        ret["mujoco_qvel_fbk"] = ret["qvel_fbk"]
        return ret
